create table if not exists users(
    id bigint generated by default as identity primary key,
    username varchar(30) NOT NULL,
    password varchar(100) NOT NULL,
    full_name varchar(50) NOT NULL,
    street varchar(50) not null,
    city varchar(50) not null,
    region varchar(20) not null,
    zip varchar(10) not null,
    phone_number varchar(20),
    role varchar(10)
);

GO;