spring:

  config:
    import: file:.env[.properties]

  thymeleaf:
    cache: false

  sql:
    init:
      mode: never

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

  cassandra:
    keyspace-name: tacocloud
    local-datacenter: datacenter1
    username: ${USERNAME}
    password: ${PASSWORD}

server:
  port: 8080