spring:

  config:
    import: file:.env[.properties]

  thymeleaf:
    cache: false


  data:
    mongodb:
      host: ${HOST}
      port: 27017
      username: ${USERNAME}
      password: ${PASSWORD}
      database: ${DATABASE}





