create table if not exists taco_order
(
    id bigint generated by default as identity primary key,
    delivery_name varchar(50) not null,
    delivery_street varchar(50) not null,
    delivery_city varchar(50) not null,
    delivery_state varchar(20) not null,
    delivery_zip varchar(10) not null,
    cc_number varchar(16) not null,
    cc_expiration varchar(5) not null,
    cccvv varchar(3) not null,
    placed_at date not null
    );

create table if not exists taco
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null,
    taco_order bigint not null,
    created_at date not null,
    CONSTRAINT taco_order_id FOREIGN KEY(taco_order) REFERENCES taco_order(id)
);

create table if not exists ingredient
(
    id varchar(4) primary key,
    name varchar(25) not null,
    type varchar(10) not null
);

create table if not exists ingredient_ref
(
    ingredient varchar(4) not null,
    taco bigint not null,
    PRIMARY KEY (taco, ingredient),
    CONSTRAINT ingredient_id FOREIGN KEY(ingredient) REFERENCES ingredient(id),
    CONSTRAINT taco_id FOREIGN KEY(taco) REFERENCES taco(id)
);

create table if not exists users(
    id bigint generated by default as identity primary key,
    username varchar(30) NOT NULL,
    password varchar(100) NOT NULL,
    full_name varchar(50) NOT NULL,
    street varchar(50) not null,
    city varchar(50) not null,
    region varchar(20) not null,
    zip varchar(10) not null,
    phone_number varchar(20),
    role varchar(10)
);

--alter table taco_order add column user_id bigint references users(id);